### ISSUE TITLE
`method` 能否以多个条件查找方法呢？

### ISSUE THREAD

**Issue by Robotxm** [fankes/YukiHookAPI#15]
大概有这么一个场景，需要 Hook 的目标 App 在旧版本和新版本中存在同名但参数列表不同的方法：

```java
// 这是旧版本 App 的方法
public static String methodName(Context context, boolean z, boolean z2)

// 这是新版本 App 的方法
public static String methodName(Context context, View view, boolean z, boolean z2, Intent intent, int i2)
```

我需要在目标 App 原本的 `methodName` 方法执行前进行一些操作。尽管新版本增加了几个参数，但这些并不是我需要用到的。也就是说除了需要 Hook 的方法签名不同之外，我不需要对我自行实现的模块中的方法进行修改。

YukiHookAPI 的文档中指出“存在多个 `BaseFinder.IndexTypeCondition` 时除了 `order` 只会生效最后一个”，这样的话我就需要将完全相同的代码复制两遍，比较繁琐。

因此，不知道能否允许通过多个 `IndexTypeCondition` 来查找方法呢？或者我的这个需求有其他的实现方法吗？

**Comment by fankes** [comment]
你可以使用 `RemedyPlan`

```kotlin
method {
    name = "methodName"
    paramCount = 3
}.remedys {
    method {
        name = "methodName"
        paramCount = 6
    }.onFind { // todo }
}.wait {
    // todo
}
```

或

```kotlin
method {
    name = "methodName"
    param(ContextClass, BooleanType, BooleanType)
}.remedys {
    method {
        name = "methodName"
        param(ContextClass, ViewClass, BooleanType, BooleanType, IntentClass, IntType)
    }.onFind { // todo }
}.wait {
    // todo
}
```

参考文档 [再次查询](https://fankes.github.io/YukiHookAPI/#/guide/special-feature?id=%e5%86%8d%e6%ac%a1%e6%9f%a5%e8%af%a2)

**Comment by Robotxm** [comment]
感谢，问题已解决。
