### ISSUE TITLE
在模块中dataChannel  wait必须要指定宿主packageName？

### ISSUE THREAD

**Issue by commiyou** [fankes/YukiHookAPI#16]
对kotlin不熟悉，大概看了下源码，好像是必须指定，广告的action中带有packageName的hashcode？
hook的目标不限定，无法指定packagename

**Comment by fankes** [comment]
没看懂，请具体描述

**Comment by commiyou** [comment]
比如我想在hook method中通过dataChannel传数据给模块，但是我想hook的应用不是限定某一个，而是很多，这个时候在mainActivity中使用dataChannel就没法指定packageName

`    dataChannel(packageName = "com.highcapable.yukihookapi.demo_app").with {
                wait(DataConst.TEST_CN_DATA) {
                    Toast.makeText(applicationContext, it, Toast.LENGTH_SHORT).show()
                }
            }`

**Comment by fankes** [comment]
请描述你的使用场景
