### ISSUE TITLE
在resources().hook中添加Long数据类型

### ISSUE THREAD

**Issue by zfdx123** [fankes/YukiHookAPI#20]
在 resources().hook -> injectResource -> conditions 的相关类型中希望添加Long数据类型

**Comment by fankes** [comment]
Resources 有 long 类型吗？

**Comment by zfdx123** [comment]
我在替换变量的过程中遇到了一个long类型的数据

**Comment by fankes** [comment]
<img width="676" alt="image" src="https://user-images.githubusercontent.com/37344460/201352156-61d7186d-c3e1-4394-b926-0d4c3adf9772.png">
Xposed API 中不存在这种类型

**Comment by zfdx123** [comment]
哦，好的谢谢，可能是我的错误，我第一次接触安卓的hook编写，谢谢您的回复，我回关闭这个issue

**Comment by fankes** [comment]
好的
