### ISSUE TITLE
JNI DETECTED ERROR IN APPLICATION: java_object == null

### ISSUE THREAD

**Issue by xihan123** [fankes/YukiHookAPI#29]
用如下代码Hook 腾讯的广告会概率出现如题的闪退(点击桌面图标直接闪退，这个时候hook貌似都没加载到这，关掉这个就不会)，特别是Android 9 以上并且在MIUI系统最为严重，我实在是找不到原因，想来问问您

```kotlin

/**
 * 免广告领取奖励
 */
fun PackageParam.freeAdReward(versionCode: Int) {
    when (versionCode) {
        in 854..878 -> {
            findClass("com.qq.e.comm.managers.plugin.PM").hook {
                injectMember {
                    method {
                        name = "getPluginClassLoader"
                        emptyParam()
                        returnType = "java.lang.ClassLoader".toClass()
                    }
                    afterHook {
                        val classLoader = result as? ClassLoader
                        classLoader?.let {
                            /**
                             * com.qq.e.comm.plugin.tangramrewardvideo.g.K() : void
                             *  int v = this.p.aQ()
                             */
                            findClass(
                                "com.qq.e.comm.plugin.tangramrewardvideo.c.b", it
                            ).hook {
                                injectMember {
                                    method {
                                        name = "p"
                                        emptyParam()
                                        returnType = IntType
                                    }
                                    replaceTo(0)
                                }
                            }

                            /**
                             * com.qq.e.comm.plugin.tangramrewardvideo.f.onAfterCreate
                             */
                            findClass("com.qq.e.comm.plugin.tangramrewardvideo.f", it).hook {
                                injectMember {
                                    method {
                                        name = "ao"
                                        emptyParam()
                                        returnType = UnitType
                                    }
                                    afterHook {

                                        val r = instance.getParam<Any>("R")
                                        val g = r?.getParam<Any>("g")
                                        val d = g?.getView<ImageView>("d")

                                        d?.postDelayed(
                                            {
                                                instance.current {
                                                    method {
                                                        name = "s"
                                                        emptyParam()
                                                    }.call()

                                                    method {
                                                        name = "onBackPressed"
                                                        emptyParam()
                                                    }.call()
                                                }
                                            },
                                            (optionEntity.mainOption.freeAdRewardAutoExitTime * 1000).toLong()
                                        )
                                    }
                                }
                            }

                            findClass(
                                "com.qq.e.comm.plugin.tangramrewardvideo.widget.j", it
                            ).hook {
                                injectMember {
                                    method {
                                        name = "b"
                                        paramCount(1)
                                        returnType = UnitType
                                    }
                                    afterHook {
                                        val h = instance.getParam<TextView>("h")
                                        h?.let { tvh ->
                                            if (tvh.text == "跳过视频") {
                                                tvh.performClick()
                                            }
                                        }
                                    }
                                }
                            }

                            findClass(
                                "com.qq.e.comm.plugin.tangramrewardvideo.c.a", it
                            ).hook {
                                injectMember {
                                    method {
                                        name = "aQ"
                                        emptyParam()
                                        returnType = IntType
                                    }
                                    replaceTo(-0x64)
                                }
                            }

                            findClass(
                                "com.qq.e.comm.plugin.tangramrewardvideo.g", it
                            ).hook {
                                injectMember {
                                    method {
                                        name = "L"
                                        emptyParam()
                                        returnType = IntType
                                    }
                                    replaceTo(0)
                                }
                            }


                        }
                    }
                }
            }

            findClass("com.qq.e.comm.managers.setting.SM").hook {
                injectMember {
                    method {
                        name = "getInteger"
                        param(StringClass, IntType)
                        returnType = IntType
                    }
                    afterHook {
                        args(1).set(0)
                    }
                }
            }
        }

        else -> "免广告领取奖励".printlnNotSupportVersion(versionCode)
    }
}
```

<details><summary>展开查看</summary><pre><code>
[ 2023-03-04T12:28:18.571        0:   857:  1336 I/LSPosedLogcat   ] New log file: /data/adb/lspd/log/verbose_2023-03-04T12:28:18.570797.log
[ 2023-03-04T12:28:22.897    10263: 22360: 22360 I/LSPosed         ] Loading xposed for com.qidian.QDReader/10263
[ 2023-03-04T12:28:22.900    10263: 22360: 22360 I/LSPosed-Bridge  ] Loading module cn.xihan.qdds from /data/app/~~U4MIEf5JRh2Q2uwjeh9XVw==/cn.xihan.qdds-rvGW3iNliX6mnvQni3zWeg==/base.apk
[ 2023-03-04T12:28:22.911    10263: 22360: 22360 I/LSPosed-Bridge  ]   Loading class cn.xihan.qdds.HookEntry_YukiHookXposedInit
[ 2023-03-04T12:28:23.389    10263: 22360:  9897 F/libc            ] Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 9897 (pool-68-thread-), pid 22360 (qidian.QDReader)
[ 2023-03-04T12:28:23.705    10263: 10153: 10153 I/LSPosed         ] Loading xposed for com.qidian.QDReader:pushcore/10263
[ 2023-03-04T12:28:23.710    10263: 10153: 10153 I/LSPosed-Bridge  ] Loading module cn.xihan.qdds from /data/app/~~U4MIEf5JRh2Q2uwjeh9XVw==/cn.xihan.qdds-rvGW3iNliX6mnvQni3zWeg==/base.apk
[ 2023-03-04T12:28:23.731    10263: 10153: 10153 I/LSPosed-Bridge  ]   Loading class cn.xihan.qdds.HookEntry_YukiHookXposedInit
[ 2023-03-04T12:28:24.261    10263:  9996:  9996 F/DEBUG           ] *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
[ 2023-03-04T12:28:24.261    10263:  9996:  9996 F/DEBUG           ] Build fingerprint: 'Xiaomi/venus/venus:13/TKQ1.220829.002/V14.0.23.2.23.DEV:user/release-keys'
[ 2023-03-04T12:28:24.261    10263:  9996:  9996 F/DEBUG           ] Revision: '0'
[ 2023-03-04T12:28:24.261    10263:  9996:  9996 F/DEBUG           ] ABI: 'arm64'
[ 2023-03-04T12:28:24.261    10263:  9996:  9996 F/DEBUG           ] Timestamp: 2023-03-04 12:28:23.454317380+0800
[ 2023-03-04T12:28:24.261    10263:  9996:  9996 F/DEBUG           ] Process uptime: 318s
[ 2023-03-04T12:28:24.261    10263:  9996:  9996 F/DEBUG           ] Cmdline: com.qidian.QDReader
[ 2023-03-04T12:28:24.261    10263:  9996:  9996 F/DEBUG           ] pid: 22360, tid: 9897, name: pool-68-thread-  >>> com.qidian.QDReader <<<
[ 2023-03-04T12:28:24.261    10263:  9996:  9996 F/DEBUG           ] uid: 10263
[ 2023-03-04T12:28:24.261    10263:  9996:  9996 F/DEBUG           ] signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
[ 2023-03-04T12:28:24.261    10263:  9996:  9996 F/DEBUG           ] Abort message: 'JNI DETECTED ERROR IN APPLICATION: java_object == null
    in call to MonitorEnter
    from boolean org.lsposed.lspd.nativebridge.HookBridge.hookMethod(java.lang.reflect.Executable, java.lang.Class, int, java.lang.Object)'
[ 2023-03-04T12:28:24.261    10263:  9996:  9996 F/DEBUG           ]     x0  0000000000000000  x1  00000000000026a9  x2  0000000000000006  x3  0000007074bf0df0
[ 2023-03-04T12:28:24.261    10263:  9996:  9996 F/DEBUG           ]     x4  5151441f43445342  x5  5151441f43445342  x6  5151441f43445342  x7  7f7f7f7f7f7f7f7f
[ 2023-03-04T12:28:24.261    10263:  9996:  9996 F/DEBUG           ]     x8  00000000000000f0  x9  00000071a94fecb0  x10 0000000000000001  x11 00000071a9573748
[ 2023-03-04T12:28:24.261    10263:  9996:  9996 F/DEBUG           ]     x12 0000007082347030  x13 0000000000deb4c8  x14 0000000000deb388  x15 0000000034155555
[ 2023-03-04T12:28:24.261    10263:  9996:  9996 F/DEBUG           ]     x16 00000071a95dea70  x17 00000071a95b73d0  x18 0000007072de0000  x19 0000000000005758
[ 2023-03-04T12:28:24.261    10263:  9996:  9996 F/DEBUG           ]     x20 00000000000026a9  x21 00000000ffffffff  x22 000000000000006e  x23 0000007074bf1008
[ 2023-03-04T12:28:24.261    10263:  9996:  9996 F/DEBUG           ]     x24 000000710c616000  x25 0000007074bf1000  x26 0000007074bf2000  x27 000000710c40b038
[ 2023-03-04T12:28:24.261    10263:  9996:  9996 F/DEBUG           ]     x28 000000710c40b268  x29 0000007074bf0e70
[ 2023-03-04T12:28:24.261    10263:  9996:  9996 F/DEBUG           ]     lr  00000071a95646c8  sp  0000007074bf0dd0  pc  00000071a95646f4  pst 0000000000001000
[ 2023-03-04T12:28:24.261    10263:  9996:  9996 F/DEBUG           ] backtrace:
[ 2023-03-04T12:28:24.261    10263:  9996:  9996 F/DEBUG           ]       #00 pc 000000000008d6f4  /apex/com.android.runtime/lib64/bionic/libc.so (abort+168) (BuildId: 2bb0d7188c0db2e8beecb24658ba9d71)
[ 2023-03-04T12:28:24.261    10263:  9996:  9996 F/DEBUG           ]       #01 pc 000000000061f104  /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+1204) (BuildId: 4ecc70344e180e7eb5404cd12fba6904)
[ 2023-03-04T12:28:24.261    10263:  9996:  9996 F/DEBUG           ]       #02 pc 0000000000017114  /apex/com.android.art/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_3::__invoke(char const*)+84) (BuildId: ef369bfbad96b532c6d8e0b144a68b96)
[ 2023-03-04T12:28:24.261    10263:  9996:  9996 F/DEBUG           ]       #03 pc 0000000000016648  /apex/com.android.art/lib64/libbase.so (android::base::LogMessage::~LogMessage()+356) (BuildId: ef369bfbad96b532c6d8e0b144a68b96)
[ 2023-03-04T12:28:24.261    10263:  9996:  9996 F/DEBUG           ]       #04 pc 0000000000459d44  /apex/com.android.art/lib64/libart.so (art::JavaVMExt::JniAbort(char const*, char const*)+2368) (BuildId: 4ecc70344e180e7eb5404cd12fba6904)
[ 2023-03-04T12:28:24.261    10263:  9996:  9996 F/DEBUG           ]       #05 pc 00000000004bfe50  /apex/com.android.art/lib64/libart.so (art::JNI<false>::MonitorEnter(_JNIEnv*, _jobject*)+1380) (BuildId: 4ecc70344e180e7eb5404cd12fba6904)
[ 2023-03-04T12:28:24.261    10263:  9996:  9996 F/DEBUG           ]       #06 pc 0000000000013c18  /memfd:jit-cache (deleted)
[ 2023-03-04T12:28:26.640    10263: 22361: 22361 I/LSPosed         ] Loading xposed for com.qidian.QDReader/10263
[ 2023-03-04T12:28:26.642    10263: 22361: 22361 I/LSPosed-Bridge  ] Loading module cn.xihan.qdds from /data/app/~~U4MIEf5JRh2Q2uwjeh9XVw==/cn.xihan.qdds-rvGW3iNliX6mnvQni3zWeg==/base.apk
[ 2023-03-04T12:28:26.654    10263: 22361: 22361 I/LSPosed-Bridge  ]   Loading class cn.xihan.qdds.HookEntry_YukiHookXposedInit
[ 2023-03-04T12:28:27.289    10263: 11141: 11141 I/LSPosed         ] Loading xposed for com.qidian.QDReader:pushcore/10263
[ 2023-03-04T12:28:27.294    10263: 11141: 11141 I/LSPosed-Bridge  ] Loading module cn.xihan.qdds from /data/app/~~U4MIEf5JRh2Q2uwjeh9XVw==/cn.xihan.qdds-rvGW3iNliX6mnvQni3zWeg==/base.apk
[ 2023-03-04T12:28:27.311    10263: 11141: 11141 I/LSPosed-Bridge  ]   Loading class cn.xihan.qdds.HookEntry_YukiHookXposedInit
[ 2023-03-04T12:28:32.698        0:   857: 23105 I/LSPosedLogcat   ] !!refresh_verbose!!

</code></pre></details>

**Comment by fankes** [comment]
这个可能是 LSPosed 或者系统的问题，和 API 无关。
