### ISSUE TITLE
在 onInit 阶段是否可以获取到 packageName 等 PackageParam 数据呢？

### ISSUE THREAD

**Issue by WankkoRee** [fankes/YukiHookAPI#3]
因为还不太了解这个开发框架的Hook生命周期，所以特地来问问。

主要是想在打日志的时候顺带输出`packageName`，然后又懒得每次传参，所以盯上了`debugTag`这个`config`。

**Comment by fankes** [comment]
`onInit` 阶段是用来初始化模块配置的，是一个代码美化的写法，你可以在任意地方配置 `configs`。
只有在 `encase` 方法内得到 `PackageParam` 实例后，也就是宿主实例，才能获取宿主的信息

**Comment by fankes** [comment]
可参考 `Wiki` 自行查看更多相关信息

**Comment by WankkoRee** [comment]
ok了解，谢谢啦！
