### ISSUE TITLE
关于XposedHelpers.set...Field

### ISSUE THREAD

**Issue by Houvven** [fankes/YukiHookAPI#30]
你好，我正在浏览并尝试使用Yukihook，但是我在api中没有发现类似于**XposedHelper.set...Field**的实现，所以想请问使用Yukihook的api我该如何实现。是否应该使用原生的Xposed api

**Comment by fankes** [comment]
这是...解决了？

**Comment by Houvven** [comment]
是的
我发现需要使用
```kotlin
Class<*>.field { name = "" }.get().set(value)
```
