### ISSUE TITLE
The new LSP Api

### ISSUE THREAD

**Issue by yangyiyu08** [fankes/YukiHookAPI#31]
现在 LSP 团队出新的 api 和 模块配置方法了，[这是示例](https://github.com/libxposed/example) 

可以适配一下吗，不然 LSP 的日志每次都提示 
`[ LSPosed-Bridge ] Loading legacy module xxx`

**Comment by fankes** [comment]
这是后期计划了，等它正式发布后再适配，现在还未发布正式版。

**Comment by yangyiyu08** [comment]
ok，再问一下，yukihook 是不是不支持 对某个对象hook，原生 Xposed 的 XposedBridge 类有个API 
```java
public static XC_MethodHook.Unhook hookMethod(Member hookMethod, XC_MethodHook callback){}
```
可以单独对某个对象的 Member hook。

找遍 yuki 的文档了，好像都没有

**Comment by fankes** [comment]
> ok，再问一下，yukihook 是不是不支持 对某个对象hook，原生 Xposed 的 XposedBridge 类有个API 
> ```java
> public static XC_MethodHook.Unhook hookMethod(Member hookMethod, XC_MethodHook callback){}
> ```
> 可以单独对某个对象的 Member hook。
> 
> 找遍 yuki 的文档了，好像都没有

请参考项目计划里的内容 `New Hook Style`

**Comment by fankes** [comment]
请参考项目计划里的内容 `New Hook Code Style`

**Comment by fankes** [comment]
现在可以这样用，因为目前的 `Class` 是只要存在即可，所以可以随便写一个，然后自己实现成员的传递：
```kotlin
PlaceholderClass.hook {
     injectMember {
         members(method { ... }.give())
         afterHook {
             // ...
         }
     }
}
```

**Comment by yangyiyu08** [comment]
原来可以用 members ，搞定了 谢谢哈

**Comment by fankes** [comment]
> 原来可以用 members ，搞定了 谢谢哈

`members` 也可以同时传递多个，因为它是 `vararg`，因为这个 Hook 方案很不好用，所以我才会计划修改它。

**Comment by yangyiyu08** [comment]
哈哈，代码没有最好只有更好，期待更新😀
