### ISSUE TITLE
Hook美团众包没效果

### ISSUE THREAD

**Issue by LiuYiGL** [fankes/YukiHookAPI#34]
美团众包的版本号：9.6.5.3347 （没加固）

用 @KyuubiRan 的 EzXHelper 去 Hook 有效果

具体代码：
```kotlin
object TestHooker : YukiBaseHooker() {
    override fun onHook() {

        "com.meituan.banma.main.activity.MainActivity".hook {
            injectMember {
                method { name("onCreate") }
                afterHook {
                    loggerD(msg = "YukiHook：执行后")
                }
            }
        }

        "com.meituan.banma.main.activity.MainActivity".toClass()
            .method { name("onCreate") }
            .give()!!.createHook {
                after {
                    loggerD(msg = "EzXHelper：执行后")
                }
            }
    }
}
```
log输出：
YukiHook：`Find Method [public void com.meituan.banma.main.activity.MainActivity.onCreate(android.os.Bundle)] takes 0ms [Default]` 但没`执行后`
EzXHelper: 有执行后

试过只用其中一个Hook，效果一样
EzXHelper 底层也是用 XposedBridge#hookMethod 的方法实现的
框架是Lsposed 1.8.5 Zygisk

实在搞不清楚是哪里出了问题

**Comment by fankes** [comment]
这里不负责解决特定 Hook 问题，有问题请去 Telegram 群组寻求帮助。

**Comment by LiuYiGL** [comment]
了解，希望作者可以优化这个问题，可能是因为有某些原因导致了Hook无效

**Comment by fankes** [comment]
#33

**Comment by LiuYiGL** [comment]
嗯嗯，lsposd 的新api 我还没怎么看，对了，刚刚补充一个，上面这个Hooker 在loadApp及以外 的作用域时，是可以生效的

但是如果在App运行时就是在生命周期中进行loadHooker的话就会无效，这是一种特性吗？

**Comment by LiuYiGL** [comment]
就我这个情况在生命周期里自己写原生的XposedBridge.hookMethod() 方法的是可以hook到的

**Comment by fankes** [comment]
等新 API 吧，我也不想研究了，之前的代码挺屎的 😂
