### ISSUE TITLE
[BUG] 无法保存键值

### ISSUE THREAD

**Issue by hujiayucc** [fankes/YukiHookAPI#35]
部分用户反馈YukiHookPrefsBridge.Editor无法保存键值

```kotlin
//Kotlin
val global: PrefsData<Boolean> = PrefsData("global", true)
prefs().edit {
    putLong("id",  0)
    put(global, item.isChecked)
}
```

```java
//Java
prefs.edit().putLong("id", 0).apply();
```

**Comment by fankes** [comment]
无效反馈，没有任何有效环境信息

**Comment by wangyuan0217** [comment]
![image](https://github.com/fankes/YukiHookAPI/assets/12730214/2d044ab7-3730-42c9-82eb-12c570b28066)
关于sp的使用疑问：
1.在点击事件中写入状态-代码不报错正常运行；
2.读取状态报错，YukiHookPrefsBridge missing Context instance

我想在软件设置的时候加个开关如上图，然后在hook的时候根据开关来判断是否执行，如下，不知是否可行；
![image](https://github.com/fankes/YukiHookAPI/assets/12730214/a9388492-e68e-453b-8730-b03b1184bf92)

目前图一读取的时候就报错了，想知道一般都是怎么使用的，谢谢
