### ISSUE TITLE
Debug环境下的log是否考虑优化一下，并且可以提供一个Hook环境判断吗？

### ISSUE THREAD

**Issue by LiuYiGL** [fankes/YukiHookAPI#40]
### log优化
目前在debug环境中，每一个回调函数的执行都会在日志上输出记录，比如
> After Hook Member [public com.android.systemui.qs.QSTileHost(android.content.Context,com.android.systemui.statusbar.phone.StatusBarIconController,com.android.systemui.plugins.qs.QSFactory,java.util.concurrent.Executor,com.android.systemui.shared.plugins.PluginManager,com.android.systemui.tuner.TunerService,javax.inject.Provider,com.android.systemui.dump.DumpManager,com.android.systemui.broadcast.BroadcastDispatcher,java.util.Optional,com.android.systemui.qs.logging.QSLogger,com.android.internal.logging.UiEventLogger,com.android.systemui.settings.UserTracker,com.android.systemui.util.settings.SecureSettings,com.android.systemui.qs.external.CustomTileStatePersister,com.android.systemui.qs.external.TileServiceRequestController$Builder,com.android.systemui.qs.external.TileLifecycleManager$Factory,com.android.systemui.plugins.statusbar.StatusBarStateController,com.android.systemui.qs.MiuiQSTileHostInjector,com.android.systemui.controlcenter.policy.ControlCenterControllerImpl)] done [Default]

但是有一些目标函数仅是简单的替换返回值为true或false之类的也会输出日志。而且io的速度是最慢的，会很影响调试的流畅性，尤其是对手势或者动画部分进行的hook

--- 
我的想法是
类似：`com.highcapable.yukihookapi.hook.core.YukiMemberHookCreator.MemberHookCreator.Result#ignoredHookingFailure`
添加一个忽略log输出的方法
然后在：`com.highcapable.yukihookapi.hook.core.YukiMemberHookCreator.MemberHookCreator#onHookLogMsg` 添加多一个判断

### Hook环境判断
当前的环境类似：
```kotlin
@YukiGenerateApi
enum class HookEntryType {

    /** 装载 Zygote */
    ZYGOTE,

    /** 装载 APP */
    PACKAGE,

    /** 装载 Resources Hook */
    RESOURCES
}
```
我发现`com.highcapable.yukihookapi.hook.entity.YukiBaseHooker#onHook`被设计在`PACKAGE` 和 `RESOURCES` 中执行，所以才会导致同样的日志会输出两个，当然hook方法应该仅对`PACKAGE`生效。所以用作者的sdk是能正常使用。但是原因和上面的log一样，在高频调用的函数下我没办法用作者的sdk进行hook，只好根据需求用原生api设计了自己的sdk：感觉风格也挺不错的hh

```kotlin
"com.test.Test".hook {
    // 第一个方法
    method {
        name = "method"
    }.before {
        // doSomeThings
    }.after {
        // doSomeThings
    }
    // 第二个方法
    method {
        name = "method"
    }.before {
        // doSomeThings
    }.after {
        // doSomeThings
    }  // 链式调用 方法异常监听、设置TAG、忽略异常等
}  // 链式调用 类异常监听，如找不到类之类的
```
由于默认在`PACKAGE` 和 `RESOURCES`中执行的原因，上面的自定义方式hook会被执行两遍，而且在运行时也会执行两遍。。。
我希望可以在Hooker下可以提供一个能判断当前环境的api，或者让我可以在hook时使用变量设置自己的hook环境

**Comment by fankes** [comment]
debug 功能目前只是为了打印 hook 成功与否，你可以自己去实现那些监听，一般情况下我们不建议启用 debug 模式，且该行为和功能都没有意义，后期会增加具体的内部日志输出选项，所以还是建议非必要情况下请关闭 debug 模式。

**Comment by fankes** [comment]
关于忽略日志这个功能，会被按照类别添加到 YukiHookLogger.Configs 中。

**Comment by fankes** [comment]
关于当前所处于什么环境的问题，还是综上所述，根据内容自动识别，资源钩子在后期应该会被移除。

**Comment by fankes** [comment]
综合考虑，添加这个功能无意义，下个版本将默认关闭 `isDebug`
