### ISSUE TITLE
YukiHookPrefsBridge missing Context instance

### ISSUE THREAD

**Issue by wangyuan0217** [fankes/YukiHookAPI#42]
![image](https://github.com/fankes/YukiHookAPI/assets/12730214/66b348db-c92b-436e-a07f-1eebebd6e56d)
关于sp的使用疑问：
1.在点击事件中写入状态-代码不报错正常运行；
2.读取状态报错，YukiHookPrefsBridge missing Context instance

我想在软件设置的时候加个开关如上图，然后在hook的时候根据开关来判断是否执行，如下，不知是否可行；
![image](https://github.com/fankes/YukiHookAPI/assets/12730214/a9388492-e68e-453b-8730-b03b1184bf92)

目前图一读取的时候就报错了，想知道一般都是怎么使用的，谢谢

_Originally posted by @wangyuan0217 in https://github.com/fankes/YukiHookAPI/issues/35#issuecomment-1679887301_

**Comment by fankes** [comment]
请仔细阅读文档，谢谢

**Comment by wangyuan0217** [comment]
![image](https://github.com/fankes/YukiHookAPI/assets/12730214/a95ff8e1-8a4f-4627-b6e5-35d9de341129)
文档就是这么写的吧。。
