### ISSUE TITLE
Need help, prefs doesn`t work

### ISSUE THREAD

**Issue by alexeigit** [fankes/YukiHookAPI#50]
Could you please help? In the module app, I set prefs. But it doesn't work in the host app. The hook is working, but `prefs.getString(Constants.KEY_ID)` always returns an empty string.

**Module App**
```
class MainActivity : BaseActivity<ActivityMainBinding>() {

    override fun onCreate() {
       ...
        val button = findViewById<Button>(R.id.setup)

        button.setOnClickListener {
            prefs().edit {
                putString(KEY_ID, androidIdText.text.toString()).apply()
            }
        }
    }
...
```
**Host App**
```
override fun onHook() = encase {

        classOf<Settings.Secure>().hook {
            injectMember {
                method {
                    name = "getString"
                }.all()

                beforeHook {
                    result = prefs.getString(Constants.KEY_ID)
                }
            }
        }
```

**Manifest**
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="org.naggi.devicex">

    <application
        android:name=".application.DefaultApplication"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/Theme.AppDefault"
        tools:targetApi="31">

        <meta-data
            android:name="xposedsharedprefs"
            android:value="true" />
        <meta-data
            android:name="xposedscope"
            android:resource="@array/module_scope" />
        <meta-data
            android:name="xposeddescription"
            android:value="@string/xposed_desc" />
        <meta-data
            android:name="xposedminversion"
            android:value="93" />

        <activity
            android:name=".ui.activity.MainActivity"
            android:exported="true"
            android:screenOrientation="behind">

            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="de.robv.android.xposed.category.MODULE_SETTINGS" />
            </intent-filter>
        </activity>

        <activity-alias
            android:name=".Home"
            android:exported="true"
            android:label="@string/app_name"
            android:screenOrientation="behind"
            android:targetActivity=".ui.activity.MainActivity">

            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity-alias>
    </application>
</manifest>
```

**Comment by fankes** [comment]
The New XSharedPreferences supported by @LSPosed, any other Xposed Frameworks may not work, since you did not provide valid information, we cannot know your operating environment. This problem cannot be solved by us. It depends on your device and the framework version used, as well as the `selinux` status of the device.

**Comment by alexeigit** [comment]
I have LSPosed, 
Redmi Note 8 Pro miui_BEGONIAGlobal_V12.5.3.0.RGGMIXM_df08917776_11.0 
latest Magysk root, 
selinux : Enforcing

**Comment by fankes** [comment]
Sorry, the only thing I can do to help you is to check whether a long uuid name is successfully generated in `/data/misc/[a very long uuid name]`, which is where LSPosed's New XSharedPreferences is stored. If it is successfully generated, please check whether the permissions of the entire directory are correct and observe the console whether any warning appear.

**Comment by alexeigit** [comment]
Thank you, will check

**Comment by naicfeng** [comment]
android 14 下 [New XSharedPreferences](https://github.com/LSPosed/LSPosed/wiki/New-XSharedPreferences) 已经失效了，现在lsposed推荐使用Modern API Remote Preferences，请问是否有计划更新？

具体表现为使用本API的模块，把配置写入了自身目录下面而不是misc目录 （降级为了[XSharedPreferences](https://api.xposed.info/reference/de/robv/android/xposed/XSharedPreferences.html)？但是debug版(模块,非lsposed)却可以写入），
手动复制配置文件到misc对应目录下面，被hook的应用可以读取

#31 #45

**Comment by fankes** [comment]
> android 14 下 [New XSharedPreferences](https://github.com/LSPosed/LSPosed/wiki/New-XSharedPreferences) 已经失效了，现在lsposed推荐使用Modern API Remote Preferences，请问是否有计划更新？
> 
> 具体表现为使用本API的模块，把配置写入了自身目录下面而不是misc目录 （降级为了[XSharedPreferences](https://api.xposed.info/reference/de/robv/android/xposed/XSharedPreferences.html)？但是debug版(模块,非lsposed)却可以写入）， 手动复制配置文件到misc对应目录下面，被hook的应用可以读取
> 
> #31 #45

请使用其它方式存储模块数据，或将自己注入到宿主里，用宿主的 Sp 存数据。

关于 Modern Xposed API 和数据存储，请查阅如下页面，有问题看文档，文档里都有写，我也不是客服不能一一回复，请自己多动动手。

(1) https://highcapable.github.io/YukiHookAPI/zh-cn/guide/supportive

(2) https://highcapable.github.io/YukiHookAPI/zh-cn/about/future#yukihookprefsbridge

**Comment by naicfeng** [comment]
> > android 14 下 [New XSharedPreferences](https://github.com/LSPosed/LSPosed/wiki/New-XSharedPreferences) 已经失效了，现在lsposed推荐使用Modern API Remote Preferences，请问是否有计划更新？
> > 具体表现为使用本API的模块，把配置写入了自身目录下面而不是misc目录 （降级为了[XSharedPreferences](https://api.xposed.info/reference/de/robv/android/xposed/XSharedPreferences.html)？但是debug版(模块,非lsposed)却可以写入）， 手动复制配置文件到misc对应目录下面，被hook的应用可以读取
> > #31 #45
> 
> 请使用其它方式存储模块数据，或将自己注入到宿主里，用宿主的 Sp 存数据。
> 
> 关于 Modern Xposed API 和数据存储，请查阅如下页面，有问题看文档，文档里都有写，我也不是客服不能一一回复，请自己多动动手。
> 
> (1) https://highcapable.github.io/YukiHookAPI/zh-cn/guide/supportive
> 
> (2) https://highcapable.github.io/YukiHookAPI/zh-cn/about/future#yukihookprefsbridge

谢谢

**Comment by fankes** [comment]
我试过在模拟器的 API 34 中 [New XSharedPreferences](https://github.com/LSPosed/LSPosed/wiki/New-XSharedPreferences) 运行正常，用我自己的模块测试的，LSPosed API 100。

![image](https://github.com/HighCapable/YukiHookAPI/assets/37344460/f31806e9-d0db-4ae8-a76f-a1d1a61adfb1)

**Comment by naicfeng** [comment]
> 我试过在模拟器的 API 34 中 [New XSharedPreferences](https://github.com/LSPosed/LSPosed/wiki/New-XSharedPreferences) 运行正常，用我自己的模块测试的，LSPosed API 100。
> 
> <img alt="image" width="258" src="https://user-images.githubusercontent.com/37344460/273458251-d9d20f5a-1326-4593-8d1d-d00dc4e50169.png">

lsp的西大师也说a14正常，但实际是很多群已经反应这个问题了
我用MIUINativeNotifyIcon，RestoreSplashScreen和cemiuiler的xsp都存在这个问题

![微信图片_20231009105725](https://github.com/HighCapable/YukiHookAPI/assets/18218380/e1857cfb-d625-4456-92b7-f9a1add50630)
![微信图片_20231009105916](https://github.com/HighCapable/YukiHookAPI/assets/18218380/2a78b850-c9b8-43d9-aee1-6ce6df6a53a8)

**Comment by fankes** [comment]
可能是异常跟踪操作的对象是系统框架。

你可以加一下 README 页面的 Telegram，尽量别打扰这层的用户了。
